/**
 * ============================================================================
 * DEMO COMPANY CONTENT — Müller & Schmidt Consulting GmbH
 * ============================================================================
 *
 * Purpose:  Realistic German Mittelstand seed data for the klargehalt Basis-tier
 *           sales demo (45 employees, 5 departments, fully populated comp
 *           structure + decision trail + info requests + audit log).
 *
 * Story arc (for the live demo):
 *   1. "Hier ist die Firma, 45 MA, 5 Abteilungen."   → companies, departments
 *   2. "Volle Comp-Struktur, vom Junior bis zum Principal."
 *                                                    → job_levels, job_profiles, pay_bands
 *   3. "Die Pay-Equity-View flaggt 2 Lücken > 5%."   → employees (Gap-Gruppen A & B)
 *   4. "Für alle anderen: dokumentierter Decision-Trail."
 *                                                    → salary_decisions
 *   5. "3 Auskunftsanfragen — offen / beantwortet / überfällig."
 *                                                    → info_requests
 *   6. "Jede Aktion im Audit-Log."                   → audit_logs
 *
 * Engineered pay gaps (intentional, demo-relevant):
 *   ─ Gap-Gruppe A: Software Engineer · Senior (Engineering, Berlin)
 *       ♂ 4 men   avg ~88.0k EUR
 *       ♀ 3 women avg ~78.5k EUR  →  ~10.8% mean gap   → FLAGGED (>5%, Art. 10)
 *   ─ Gap-Gruppe B: Account Executive · Mid (Vertrieb, München)
 *       ♂ 3 men   avg ~66.0k EUR
 *       ♀ 2 women avg ~58.0k EUR  →  ~12.1% mean gap   → FLAGGED (>5%, Art. 10)
 *   ─ All other (profile × level) groups are within ±3% → "explainable" cohort.
 *
 * Placeholders:
 *   {{ORG_ID}}      — Logto organization id, e.g. "org_xxx" (filled by seeder)
 *   {{OWNER_USER}}  — demo owner Logto sub id, e.g. "user_xxx" (filled by seeder)
 *   {{HR_USER}}     — second seat (HR manager) Logto sub id
 *   {{uuid_*}}      — table-local uuid placeholders (cross-referenced by name)
 *
 * Reference notes embedded in employee `_note` fields explain which row
 * belongs to which gap-group / band / decision target.
 * ============================================================================
 */

// ─────────────────────────────────────────────────────────────────────────────
// 1. COMPANY
// ─────────────────────────────────────────────────────────────────────────────

export const company = {
  id: '{{uuid_company}}',
  organization_id: '{{ORG_ID}}',
  name: 'Müller & Schmidt Consulting',
  legal_name: 'Müller & Schmidt Consulting GmbH',
  country: 'DE',
  industry: 'Management- & Technologieberatung',
  employee_size_band: '1-49',
  reporting_frequency: 'voluntary', // Basis-Tier → keine Berichtspflicht
  subscription_tier: 'basis',
  subscription_status: 'active',
  // Demo-meta (nicht in DB) ───────────────────────────────────
  _address: 'Friedrichstraße 68, 10117 Berlin',
  _founded: 2014,
  _hq_city: 'Berlin',
  _secondary_office: 'München (Maximilianstraße 13, 80539 München)',
  _contact_email: 'kontakt@mueller-schmidt.de',
  _website: 'https://mueller-schmidt.de',
  _ceo: 'Dr. Katharina Müller',
  _hr_lead: 'Sandra Becker', // wird im Demo als Owner eingeloggt
  _employee_email_domain: 'mueller-schmidt.de',
  _pitch: 'Mittelständische Boutique-Beratung für digitale Transformation & SaaS-Strategie.',
} as const;

// ─────────────────────────────────────────────────────────────────────────────
// 2. DEPARTMENTS  (5 — sum of headcount = 45)
// ─────────────────────────────────────────────────────────────────────────────
//   Engineering 16  ·  Vertrieb 10  ·  Marketing 6  ·  HR & Operations 7  ·  Finanzen 6

export const departments = [
  {
    id: '{{uuid_dept_eng}}',
    organization_id: '{{ORG_ID}}',
    name: 'Engineering',
    _headcount: 16,
    _note: 'Größtes Team. Hier liegt Gap-Gruppe A (Software Engineer Senior).',
  },
  {
    id: '{{uuid_dept_sales}}',
    organization_id: '{{ORG_ID}}',
    name: 'Vertrieb',
    _headcount: 10,
    _note: 'Hier liegt Gap-Gruppe B (Account Executive Mid).',
  },
  {
    id: '{{uuid_dept_marketing}}',
    organization_id: '{{ORG_ID}}',
    name: 'Marketing',
    _headcount: 6,
  },
  {
    id: '{{uuid_dept_hr}}',
    organization_id: '{{ORG_ID}}',
    name: 'HR & Operations',
    _headcount: 7,
    _note: 'Owner (Sandra Becker) sitzt hier; ein zweiter HR-Manager-Seat.',
  },
  {
    id: '{{uuid_dept_finance}}',
    organization_id: '{{ORG_ID}}',
    name: 'Finanzen',
    _headcount: 6,
  },
] as const;

// ─────────────────────────────────────────────────────────────────────────────
// 3. JOB LEVELS  (5, ranked 1..5)
// ─────────────────────────────────────────────────────────────────────────────

export const jobLevels = [
  {
    id: '{{uuid_lvl_junior}}',
    organization_id: '{{ORG_ID}}',
    name: 'Junior',
    rank: 1,
    _band_marker_eur: '42.000 – 55.000',
  },
  {
    id: '{{uuid_lvl_mid}}',
    organization_id: '{{ORG_ID}}',
    name: 'Mid',
    rank: 2,
    _band_marker_eur: '55.000 – 72.000',
  },
  {
    id: '{{uuid_lvl_senior}}',
    organization_id: '{{ORG_ID}}',
    name: 'Senior',
    rank: 3,
    _band_marker_eur: '70.000 – 95.000',
  },
  {
    id: '{{uuid_lvl_lead}}',
    organization_id: '{{ORG_ID}}',
    name: 'Lead',
    rank: 4,
    _band_marker_eur: '90.000 – 115.000',
  },
  {
    id: '{{uuid_lvl_principal}}',
    organization_id: '{{ORG_ID}}',
    name: 'Principal',
    rank: 5,
    _band_marker_eur: '110.000 – 145.000',
  },
] as const;

// ─────────────────────────────────────────────────────────────────────────────
// 4. JOB PROFILES  (12 — meaningful spread across all 5 departments)
// ─────────────────────────────────────────────────────────────────────────────
//   skills/effort/responsibility/working_conditions on a 1..5 scale
//   (used by job_profile_evaluation for "gleichwertige Arbeit").

export const jobProfiles = [
  // Engineering (4 profiles) ─────────────────────────────────
  {
    id: '{{uuid_jp_swe}}',
    organization_id: '{{ORG_ID}}',
    title: 'Software Engineer',
    description: 'Softwareentwicklung im Produktteam (Fullstack, TypeScript/Next.js).',
    department_id: '{{uuid_dept_eng}}',
    skills_score: 4,
    effort_score: 3,
    responsibility_score: 3,
    working_conditions_score: 2,
    is_active: true,
  },
  {
    id: '{{uuid_jp_devops}}',
    organization_id: '{{ORG_ID}}',
    title: 'DevOps Engineer',
    description: 'CI/CD, Infrastruktur, Observability (AWS/GCP, Terraform).',
    department_id: '{{uuid_dept_eng}}',
    skills_score: 4,
    effort_score: 3,
    responsibility_score: 4,
    working_conditions_score: 2,
    is_active: true,
  },
  {
    id: '{{uuid_jp_pm}}',
    organization_id: '{{ORG_ID}}',
    title: 'Product Manager',
    description: 'Produktstrategie, Roadmap, Discovery — schnittstellig zu Engineering & Vertrieb.',
    department_id: '{{uuid_dept_eng}}',
    skills_score: 4,
    effort_score: 3,
    responsibility_score: 4,
    working_conditions_score: 2,
    is_active: true,
  },
  {
    id: '{{uuid_jp_qa}}',
    organization_id: '{{ORG_ID}}',
    title: 'QA Engineer',
    description: 'Test-Automatisierung, Quality Gates, E2E-Tests.',
    department_id: '{{uuid_dept_eng}}',
    skills_score: 3,
    effort_score: 3,
    responsibility_score: 3,
    working_conditions_score: 2,
    is_active: true,
  },
  // Vertrieb (2 profiles) ─────────────────────────────────────
  {
    id: '{{uuid_jp_ae}}',
    organization_id: '{{ORG_ID}}',
    title: 'Account Executive',
    description: 'B2B-Vertrieb für Bestands- und Neukunden, Closing-verantwortlich.',
    department_id: '{{uuid_dept_sales}}',
    skills_score: 3,
    effort_score: 4,
    responsibility_score: 4,
    working_conditions_score: 3,
    is_active: true,
  },
  {
    id: '{{uuid_jp_sdr}}',
    organization_id: '{{ORG_ID}}',
    title: 'Sales Development Representative',
    description: 'Outbound-Prospecting, Pipeline-Aufbau, Qualifizierung.',
    department_id: '{{uuid_dept_sales}}',
    skills_score: 2,
    effort_score: 4,
    responsibility_score: 2,
    working_conditions_score: 3,
    is_active: true,
  },
  // Marketing (2 profiles) ────────────────────────────────────
  {
    id: '{{uuid_jp_mkt_mgr}}',
    organization_id: '{{ORG_ID}}',
    title: 'Marketing Manager',
    description: 'Demand Generation, Content & Performance Marketing.',
    department_id: '{{uuid_dept_marketing}}',
    skills_score: 3,
    effort_score: 3,
    responsibility_score: 3,
    working_conditions_score: 2,
    is_active: true,
  },
  {
    id: '{{uuid_jp_content}}',
    organization_id: '{{ORG_ID}}',
    title: 'Content Specialist',
    description: 'Redaktion, SEO-Content, Whitepapers & Webinare.',
    department_id: '{{uuid_dept_marketing}}',
    skills_score: 3,
    effort_score: 2,
    responsibility_score: 2,
    working_conditions_score: 2,
    is_active: true,
  },
  // HR & Operations (2 profiles) ──────────────────────────────
  {
    id: '{{uuid_jp_hrbp}}',
    organization_id: '{{ORG_ID}}',
    title: 'HR Business Partner',
    description: 'Beratung Führungskräfte, Recruiting, People Operations.',
    department_id: '{{uuid_dept_hr}}',
    skills_score: 3,
    effort_score: 3,
    responsibility_score: 4,
    working_conditions_score: 2,
    is_active: true,
  },
  {
    id: '{{uuid_jp_office}}',
    organization_id: '{{ORG_ID}}',
    title: 'Office & Operations Manager',
    description: 'Office Management, Onboarding-Logistik, Lieferantensteuerung.',
    department_id: '{{uuid_dept_hr}}',
    skills_score: 2,
    effort_score: 3,
    responsibility_score: 2,
    working_conditions_score: 2,
    is_active: true,
  },
  // Finanzen (2 profiles) ─────────────────────────────────────
  {
    id: '{{uuid_jp_controller}}',
    organization_id: '{{ORG_ID}}',
    title: 'Finanzcontroller',
    description: 'Budget, Forecast, Reporting; Begleitung Jahresabschluss.',
    department_id: '{{uuid_dept_finance}}',
    skills_score: 4,
    effort_score: 3,
    responsibility_score: 4,
    working_conditions_score: 2,
    is_active: true,
  },
  {
    id: '{{uuid_jp_accountant}}',
    organization_id: '{{ORG_ID}}',
    title: 'Buchhalter:in',
    description: 'Debitoren-/Kreditorenbuchhaltung, USt-Voranmeldung.',
    department_id: '{{uuid_dept_finance}}',
    skills_score: 3,
    effort_score: 3,
    responsibility_score: 3,
    working_conditions_score: 2,
    is_active: true,
  },
] as const;

// ─────────────────────────────────────────────────────────────────────────────
// 5. PAY BANDS  (14 — only the (profile × level) combos that actually have employees)
// ─────────────────────────────────────────────────────────────────────────────
//   effective_from = 2026-01-01 for all (current fiscal year)
//   currency = EUR  ·  is_active = true

export const payBands = [
  // Engineering · Software Engineer ──────────────────────────
  {
    id: '{{uuid_pb_swe_jr}}',
    organization_id: '{{ORG_ID}}',
    job_profile_id: '{{uuid_jp_swe}}',
    job_level_id: '{{uuid_lvl_junior}}',
    min_salary: 48000,
    max_salary: 58000,
    _median: 53000,
    effective_from: '2026-01-01',
    _note: 'Software Engineer · Junior',
  },
  {
    id: '{{uuid_pb_swe_mid}}',
    organization_id: '{{ORG_ID}}',
    job_profile_id: '{{uuid_jp_swe}}',
    job_level_id: '{{uuid_lvl_mid}}',
    min_salary: 62000,
    max_salary: 78000,
    _median: 70000,
    effective_from: '2026-01-01',
    _note: 'Software Engineer · Mid',
  },
  {
    id: '{{uuid_pb_swe_sr}}',
    organization_id: '{{ORG_ID}}',
    job_profile_id: '{{uuid_jp_swe}}',
    job_level_id: '{{uuid_lvl_senior}}',
    min_salary: 75000,
    max_salary: 95000,
    _median: 85000,
    effective_from: '2026-01-01',
    _note: 'Software Engineer · Senior  ← GAP-GRUPPE A',
  },
  {
    id: '{{uuid_pb_swe_lead}}',
    organization_id: '{{ORG_ID}}',
    job_profile_id: '{{uuid_jp_swe}}',
    job_level_id: '{{uuid_lvl_lead}}',
    min_salary: 95000,
    max_salary: 118000,
    _median: 108000,
    effective_from: '2026-01-01',
    _note: 'Software Engineer · Lead',
  },
  // Engineering · DevOps Engineer ────────────────────────────
  {
    id: '{{uuid_pb_devops_mid}}',
    organization_id: '{{ORG_ID}}',
    job_profile_id: '{{uuid_jp_devops}}',
    job_level_id: '{{uuid_lvl_mid}}',
    min_salary: 65000,
    max_salary: 82000,
    _median: 74000,
    effective_from: '2026-01-01',
  },
  {
    id: '{{uuid_pb_devops_sr}}',
    organization_id: '{{ORG_ID}}',
    job_profile_id: '{{uuid_jp_devops}}',
    job_level_id: '{{uuid_lvl_senior}}',
    min_salary: 80000,
    max_salary: 100000,
    _median: 90000,
    effective_from: '2026-01-01',
  },
  // Engineering · Product Manager ────────────────────────────
  {
    id: '{{uuid_pb_pm_sr}}',
    organization_id: '{{ORG_ID}}',
    job_profile_id: '{{uuid_jp_pm}}',
    job_level_id: '{{uuid_lvl_senior}}',
    min_salary: 82000,
    max_salary: 102000,
    _median: 92000,
    effective_from: '2026-01-01',
  },
  {
    id: '{{uuid_pb_pm_principal}}',
    organization_id: '{{ORG_ID}}',
    job_profile_id: '{{uuid_jp_pm}}',
    job_level_id: '{{uuid_lvl_principal}}',
    min_salary: 115000,
    max_salary: 142000,
    _median: 128000,
    effective_from: '2026-01-01',
  },
  // Engineering · QA Engineer ────────────────────────────────
  {
    id: '{{uuid_pb_qa_mid}}',
    organization_id: '{{ORG_ID}}',
    job_profile_id: '{{uuid_jp_qa}}',
    job_level_id: '{{uuid_lvl_mid}}',
    min_salary: 55000,
    max_salary: 68000,
    _median: 61000,
    effective_from: '2026-01-01',
  },
  // Vertrieb · Account Executive ─────────────────────────────
  {
    id: '{{uuid_pb_ae_mid}}',
    organization_id: '{{ORG_ID}}',
    job_profile_id: '{{uuid_jp_ae}}',
    job_level_id: '{{uuid_lvl_mid}}',
    min_salary: 52000,
    max_salary: 72000,
    _median: 62000,
    effective_from: '2026-01-01',
    _note: 'Account Executive · Mid  ← GAP-GRUPPE B (Base ohne OTE)',
  },
  {
    id: '{{uuid_pb_ae_sr}}',
    organization_id: '{{ORG_ID}}',
    job_profile_id: '{{uuid_jp_ae}}',
    job_level_id: '{{uuid_lvl_senior}}',
    min_salary: 72000,
    max_salary: 95000,
    _median: 83000,
    effective_from: '2026-01-01',
  },
  // Vertrieb · SDR ───────────────────────────────────────────
  {
    id: '{{uuid_pb_sdr_jr}}',
    organization_id: '{{ORG_ID}}',
    job_profile_id: '{{uuid_jp_sdr}}',
    job_level_id: '{{uuid_lvl_junior}}',
    min_salary: 42000,
    max_salary: 52000,
    _median: 47000,
    effective_from: '2026-01-01',
  },
  // Marketing · Marketing Manager ────────────────────────────
  {
    id: '{{uuid_pb_mkt_mid}}',
    organization_id: '{{ORG_ID}}',
    job_profile_id: '{{uuid_jp_mkt_mgr}}',
    job_level_id: '{{uuid_lvl_mid}}',
    min_salary: 55000,
    max_salary: 72000,
    _median: 63000,
    effective_from: '2026-01-01',
  },
  {
    id: '{{uuid_pb_mkt_sr}}',
    organization_id: '{{ORG_ID}}',
    job_profile_id: '{{uuid_jp_mkt_mgr}}',
    job_level_id: '{{uuid_lvl_senior}}',
    min_salary: 72000,
    max_salary: 92000,
    _median: 82000,
    effective_from: '2026-01-01',
  },
  // Marketing · Content Specialist ───────────────────────────
  {
    id: '{{uuid_pb_content_jr}}',
    organization_id: '{{ORG_ID}}',
    job_profile_id: '{{uuid_jp_content}}',
    job_level_id: '{{uuid_lvl_junior}}',
    min_salary: 42000,
    max_salary: 52000,
    _median: 47000,
    effective_from: '2026-01-01',
  },
  // HR · HRBP ────────────────────────────────────────────────
  {
    id: '{{uuid_pb_hrbp_sr}}',
    organization_id: '{{ORG_ID}}',
    job_profile_id: '{{uuid_jp_hrbp}}',
    job_level_id: '{{uuid_lvl_senior}}',
    min_salary: 70000,
    max_salary: 88000,
    _median: 79000,
    effective_from: '2026-01-01',
  },
  {
    id: '{{uuid_pb_hrbp_lead}}',
    organization_id: '{{ORG_ID}}',
    job_profile_id: '{{uuid_jp_hrbp}}',
    job_level_id: '{{uuid_lvl_lead}}',
    min_salary: 92000,
    max_salary: 115000,
    _median: 104000,
    effective_from: '2026-01-01',
  },
  // HR · Office & Operations ─────────────────────────────────
  {
    id: '{{uuid_pb_office_jr}}',
    organization_id: '{{ORG_ID}}',
    job_profile_id: '{{uuid_jp_office}}',
    job_level_id: '{{uuid_lvl_junior}}',
    min_salary: 38000,
    max_salary: 48000,
    _median: 43000,
    effective_from: '2026-01-01',
  },
  // Finanzen · Controller ────────────────────────────────────
  {
    id: '{{uuid_pb_controller_sr}}',
    organization_id: '{{ORG_ID}}',
    job_profile_id: '{{uuid_jp_controller}}',
    job_level_id: '{{uuid_lvl_senior}}',
    min_salary: 78000,
    max_salary: 98000,
    _median: 88000,
    effective_from: '2026-01-01',
  },
  {
    id: '{{uuid_pb_controller_mid}}',
    organization_id: '{{ORG_ID}}',
    job_profile_id: '{{uuid_jp_controller}}',
    job_level_id: '{{uuid_lvl_mid}}',
    min_salary: 60000,
    max_salary: 75000,
    _median: 68000,
    effective_from: '2026-01-01',
  },
  // Finanzen · Buchhalter:in ─────────────────────────────────
  {
    id: '{{uuid_pb_accountant_mid}}',
    organization_id: '{{ORG_ID}}',
    job_profile_id: '{{uuid_jp_accountant}}',
    job_level_id: '{{uuid_lvl_mid}}',
    min_salary: 52000,
    max_salary: 65000,
    _median: 58000,
    effective_from: '2026-01-01',
  },
] as const;

// ─────────────────────────────────────────────────────────────────────────────
// 6. EMPLOYEES  (45)
// ─────────────────────────────────────────────────────────────────────────────
//   Gender mix  : 25 male  /  20 female   ≈ 56% / 44%
//   Engineered gaps:
//     ─ #07–#13  Gap-Gruppe A  (Software Engineer · Senior)
//         ♂ M: Lukas Bauer 90k · Tobias Krüger 86k · Stefan Wagner 89k · Christian Vogel 87k → avg 88.0k
//         ♀ F: Anna Schulz 80k · Lena Hofmann 79k · Julia Richter 76.5k                      → avg 78.5k
//         mean gap = (88 - 78.5) / 88 ≈ 10.8%   → flagged
//     ─ #17–#21  Gap-Gruppe B  (Account Executive · Mid)
//         ♂ M: David Lehmann 67k · Florian Beck 65k · Sebastian Roth 66k                      → avg 66.0k
//         ♀ F: Marie Köhler 58.5k · Nicole Schäfer 57.5k                                       → avg 58.0k
//         mean gap = (66 - 58) / 66 ≈ 12.1%   → flagged
//
//   All other (profile×level) cohorts are within ±3% — "clean" reference cohorts.
//   employment_type "full_time" default; weekly_hours 40 unless noted.

export const employees = [
  // ── HR & Operations (7) ───────────────────────────────────
  {
    _idx: 1,
    id: '{{uuid_emp_01}}',
    organization_id: '{{ORG_ID}}',
    employee_number: 'MS-001',
    first_name: 'Sandra',
    last_name: 'Becker',
    email: 'sandra.becker@mueller-schmidt.de',
    gender: 'female',
    birth_year: 1982,
    job_profile_id: '{{uuid_jp_hrbp}}',
    job_level_id: '{{uuid_lvl_lead}}',
    department_id: '{{uuid_dept_hr}}',
    employment_type: 'full_time',
    location: 'Berlin',
    hire_date: '2018-04-01',
    base_salary: 102000,
    variable_pay: 8000,
    pay_band_id: '{{uuid_pb_hrbp_lead}}',
    user_id: '{{OWNER_USER}}',
    _note: 'Owner / HR Lead — wird im Demo eingeloggt.',
  },
  {
    _idx: 2,
    id: '{{uuid_emp_02}}',
    organization_id: '{{ORG_ID}}',
    employee_number: 'MS-002',
    first_name: 'Markus',
    last_name: 'Hofer',
    email: 'markus.hofer@mueller-schmidt.de',
    gender: 'male',
    birth_year: 1985,
    job_profile_id: '{{uuid_jp_hrbp}}',
    job_level_id: '{{uuid_lvl_senior}}',
    department_id: '{{uuid_dept_hr}}',
    employment_type: 'full_time',
    location: 'Berlin',
    hire_date: '2020-09-15',
    base_salary: 80000,
    variable_pay: 4000,
    pay_band_id: '{{uuid_pb_hrbp_sr}}',
    user_id: '{{HR_USER}}',
    _note: 'Zweiter Seat (hr_manager).',
  },
  {
    _idx: 3,
    id: '{{uuid_emp_03}}',
    organization_id: '{{ORG_ID}}',
    employee_number: 'MS-003',
    first_name: 'Petra',
    last_name: 'Wolf',
    email: 'petra.wolf@mueller-schmidt.de',
    gender: 'female',
    birth_year: 1991,
    job_profile_id: '{{uuid_jp_office}}',
    job_level_id: '{{uuid_lvl_junior}}',
    department_id: '{{uuid_dept_hr}}',
    employment_type: 'full_time',
    location: 'Berlin',
    hire_date: '2022-02-01',
    base_salary: 44000,
    pay_band_id: '{{uuid_pb_office_jr}}',
  },
  {
    _idx: 4,
    id: '{{uuid_emp_04}}',
    organization_id: '{{ORG_ID}}',
    employee_number: 'MS-004',
    first_name: 'Jana',
    last_name: 'Albrecht',
    email: 'jana.albrecht@mueller-schmidt.de',
    gender: 'female',
    birth_year: 1993,
    job_profile_id: '{{uuid_jp_office}}',
    job_level_id: '{{uuid_lvl_junior}}',
    department_id: '{{uuid_dept_hr}}',
    employment_type: 'part_time',
    weekly_hours: 30,
    location: 'München',
    hire_date: '2023-05-15',
    base_salary: 33000, // FTE-equivalent ~44k, pro-rata 30h/40h
    pay_band_id: '{{uuid_pb_office_jr}}',
    _note: 'Part-time 30h, sauber dokumentiert.',
  },
  {
    _idx: 5,
    id: '{{uuid_emp_05}}',
    organization_id: '{{ORG_ID}}',
    employee_number: 'MS-005',
    first_name: 'Thomas',
    last_name: 'Schmidt',
    email: 'thomas.schmidt@mueller-schmidt.de',
    gender: 'male',
    birth_year: 1989,
    job_profile_id: '{{uuid_jp_office}}',
    job_level_id: '{{uuid_lvl_junior}}',
    department_id: '{{uuid_dept_hr}}',
    employment_type: 'full_time',
    location: 'Berlin',
    hire_date: '2021-10-01',
    base_salary: 45000,
    pay_band_id: '{{uuid_pb_office_jr}}',
  },
  {
    _idx: 6,
    id: '{{uuid_emp_06}}',
    organization_id: '{{ORG_ID}}',
    employee_number: 'MS-006',
    first_name: 'Yusuf',
    last_name: 'Demir',
    email: 'yusuf.demir@mueller-schmidt.de',
    gender: 'male',
    birth_year: 1987,
    job_profile_id: '{{uuid_jp_office}}',
    job_level_id: '{{uuid_lvl_junior}}',
    department_id: '{{uuid_dept_hr}}',
    employment_type: 'full_time',
    location: 'Berlin',
    hire_date: '2023-08-01',
    base_salary: 43000,
    pay_band_id: '{{uuid_pb_office_jr}}',
  },
  {
    _idx: 7,
    id: '{{uuid_emp_07}}',
    organization_id: '{{ORG_ID}}',
    employee_number: 'MS-007',
    first_name: 'Sabrina',
    last_name: 'Maier',
    email: 'sabrina.maier@mueller-schmidt.de',
    gender: 'female',
    birth_year: 1995,
    job_profile_id: '{{uuid_jp_office}}',
    job_level_id: '{{uuid_lvl_junior}}',
    department_id: '{{uuid_dept_hr}}',
    employment_type: 'full_time',
    location: 'Berlin',
    hire_date: '2024-01-15',
    base_salary: 42000,
    pay_band_id: '{{uuid_pb_office_jr}}',
    _note: 'Hat die OFFENE info_request gestellt (siehe info_requests #1).',
  },

  // ── Engineering (16) — incl. GAP-GRUPPE A (Software Engineer Senior) ──
  {
    _idx: 8,
    id: '{{uuid_emp_08}}',
    organization_id: '{{ORG_ID}}',
    employee_number: 'MS-008',
    first_name: 'Lukas',
    last_name: 'Bauer',
    email: 'lukas.bauer@mueller-schmidt.de',
    gender: 'male',
    birth_year: 1986,
    job_profile_id: '{{uuid_jp_swe}}',
    job_level_id: '{{uuid_lvl_senior}}',
    department_id: '{{uuid_dept_eng}}',
    employment_type: 'full_time',
    location: 'Berlin',
    hire_date: '2019-03-04',
    base_salary: 90000,
    variable_pay: 3000,
    pay_band_id: '{{uuid_pb_swe_sr}}',
    _note: 'GAP-GRUPPE A · ♂',
  },
  {
    _idx: 9,
    id: '{{uuid_emp_09}}',
    organization_id: '{{ORG_ID}}',
    employee_number: 'MS-009',
    first_name: 'Tobias',
    last_name: 'Krüger',
    email: 'tobias.krueger@mueller-schmidt.de',
    gender: 'male',
    birth_year: 1988,
    job_profile_id: '{{uuid_jp_swe}}',
    job_level_id: '{{uuid_lvl_senior}}',
    department_id: '{{uuid_dept_eng}}',
    employment_type: 'full_time',
    location: 'Berlin',
    hire_date: '2020-06-10',
    base_salary: 86000,
    variable_pay: 3000,
    pay_band_id: '{{uuid_pb_swe_sr}}',
    _note: 'GAP-GRUPPE A · ♂',
  },
  {
    _idx: 10,
    id: '{{uuid_emp_10}}',
    organization_id: '{{ORG_ID}}',
    employee_number: 'MS-010',
    first_name: 'Stefan',
    last_name: 'Wagner',
    email: 'stefan.wagner@mueller-schmidt.de',
    gender: 'male',
    birth_year: 1984,
    job_profile_id: '{{uuid_jp_swe}}',
    job_level_id: '{{uuid_lvl_senior}}',
    department_id: '{{uuid_dept_eng}}',
    employment_type: 'full_time',
    location: 'Berlin',
    hire_date: '2018-11-05',
    base_salary: 89000,
    variable_pay: 3000,
    pay_band_id: '{{uuid_pb_swe_sr}}',
    _note: 'GAP-GRUPPE A · ♂',
  },
  {
    _idx: 11,
    id: '{{uuid_emp_11}}',
    organization_id: '{{ORG_ID}}',
    employee_number: 'MS-011',
    first_name: 'Christian',
    last_name: 'Vogel',
    email: 'christian.vogel@mueller-schmidt.de',
    gender: 'male',
    birth_year: 1990,
    job_profile_id: '{{uuid_jp_swe}}',
    job_level_id: '{{uuid_lvl_senior}}',
    department_id: '{{uuid_dept_eng}}',
    employment_type: 'full_time',
    location: 'Berlin',
    hire_date: '2021-07-19',
    base_salary: 87000,
    variable_pay: 3000,
    pay_band_id: '{{uuid_pb_swe_sr}}',
    _note: 'GAP-GRUPPE A · ♂',
  },
  {
    _idx: 12,
    id: '{{uuid_emp_12}}',
    organization_id: '{{ORG_ID}}',
    employee_number: 'MS-012',
    first_name: 'Anna',
    last_name: 'Schulz',
    email: 'anna.schulz@mueller-schmidt.de',
    gender: 'female',
    birth_year: 1989,
    job_profile_id: '{{uuid_jp_swe}}',
    job_level_id: '{{uuid_lvl_senior}}',
    department_id: '{{uuid_dept_eng}}',
    employment_type: 'full_time',
    location: 'Berlin',
    hire_date: '2020-02-12',
    base_salary: 80000,
    variable_pay: 3000,
    pay_band_id: '{{uuid_pb_swe_sr}}',
    _note: 'GAP-GRUPPE A · ♀ — hat die ÜBERFÄLLIGE info_request gestellt (info_requests #3).',
  },
  {
    _idx: 13,
    id: '{{uuid_emp_13}}',
    organization_id: '{{ORG_ID}}',
    employee_number: 'MS-013',
    first_name: 'Lena',
    last_name: 'Hofmann',
    email: 'lena.hofmann@mueller-schmidt.de',
    gender: 'female',
    birth_year: 1991,
    job_profile_id: '{{uuid_jp_swe}}',
    job_level_id: '{{uuid_lvl_senior}}',
    department_id: '{{uuid_dept_eng}}',
    employment_type: 'full_time',
    location: 'Berlin',
    hire_date: '2021-04-01',
    base_salary: 79000,
    variable_pay: 3000,
    pay_band_id: '{{uuid_pb_swe_sr}}',
    _note: 'GAP-GRUPPE A · ♀',
  },
  {
    _idx: 14,
    id: '{{uuid_emp_14}}',
    organization_id: '{{ORG_ID}}',
    employee_number: 'MS-014',
    first_name: 'Julia',
    last_name: 'Richter',
    email: 'julia.richter@mueller-schmidt.de',
    gender: 'female',
    birth_year: 1992,
    job_profile_id: '{{uuid_jp_swe}}',
    job_level_id: '{{uuid_lvl_senior}}',
    department_id: '{{uuid_dept_eng}}',
    employment_type: 'full_time',
    location: 'Berlin',
    hire_date: '2022-01-10',
    base_salary: 76500,
    variable_pay: 3000,
    pay_band_id: '{{uuid_pb_swe_sr}}',
    _note: 'GAP-GRUPPE A · ♀',
  },
  // Engineering — Software Engineer Mid (3, ~equal pay)
  {
    _idx: 15,
    id: '{{uuid_emp_15}}',
    organization_id: '{{ORG_ID}}',
    employee_number: 'MS-015',
    first_name: 'Daniel',
    last_name: 'Klein',
    email: 'daniel.klein@mueller-schmidt.de',
    gender: 'male',
    birth_year: 1994,
    job_profile_id: '{{uuid_jp_swe}}',
    job_level_id: '{{uuid_lvl_mid}}',
    department_id: '{{uuid_dept_eng}}',
    employment_type: 'full_time',
    location: 'Berlin',
    hire_date: '2022-08-01',
    base_salary: 70000,
    pay_band_id: '{{uuid_pb_swe_mid}}',
    _note: 'Clean cohort SWE-Mid (gap <2%).',
  },
  {
    _idx: 16,
    id: '{{uuid_emp_16}}',
    organization_id: '{{ORG_ID}}',
    employee_number: 'MS-016',
    first_name: 'Verena',
    last_name: 'Braun',
    email: 'verena.braun@mueller-schmidt.de',
    gender: 'female',
    birth_year: 1995,
    job_profile_id: '{{uuid_jp_swe}}',
    job_level_id: '{{uuid_lvl_mid}}',
    department_id: '{{uuid_dept_eng}}',
    employment_type: 'full_time',
    location: 'Berlin',
    hire_date: '2022-10-15',
    base_salary: 69500,
    pay_band_id: '{{uuid_pb_swe_mid}}',
    _note: 'Clean cohort SWE-Mid (gap <2%).',
  },
  {
    _idx: 17,
    id: '{{uuid_emp_17}}',
    organization_id: '{{ORG_ID}}',
    employee_number: 'MS-017',
    first_name: 'Philipp',
    last_name: 'Neumann',
    email: 'philipp.neumann@mueller-schmidt.de',
    gender: 'male',
    birth_year: 1993,
    job_profile_id: '{{uuid_jp_swe}}',
    job_level_id: '{{uuid_lvl_mid}}',
    department_id: '{{uuid_dept_eng}}',
    employment_type: 'full_time',
    location: 'Berlin',
    hire_date: '2023-02-20',
    base_salary: 71000,
    pay_band_id: '{{uuid_pb_swe_mid}}',
  },
  // Engineering — Software Engineer Junior (2)
  {
    _idx: 18,
    id: '{{uuid_emp_18}}',
    organization_id: '{{ORG_ID}}',
    employee_number: 'MS-018',
    first_name: 'Pauline',
    last_name: 'Krause',
    email: 'pauline.krause@mueller-schmidt.de',
    gender: 'female',
    birth_year: 1998,
    job_profile_id: '{{uuid_jp_swe}}',
    job_level_id: '{{uuid_lvl_junior}}',
    department_id: '{{uuid_dept_eng}}',
    employment_type: 'full_time',
    location: 'Berlin',
    hire_date: '2024-09-01',
    base_salary: 52000,
    pay_band_id: '{{uuid_pb_swe_jr}}',
  },
  {
    _idx: 19,
    id: '{{uuid_emp_19}}',
    organization_id: '{{ORG_ID}}',
    employee_number: 'MS-019',
    first_name: 'Niklas',
    last_name: 'Schreiber',
    email: 'niklas.schreiber@mueller-schmidt.de',
    gender: 'male',
    birth_year: 1999,
    job_profile_id: '{{uuid_jp_swe}}',
    job_level_id: '{{uuid_lvl_junior}}',
    department_id: '{{uuid_dept_eng}}',
    employment_type: 'full_time',
    location: 'Berlin',
    hire_date: '2025-01-13',
    base_salary: 51000,
    pay_band_id: '{{uuid_pb_swe_jr}}',
  },
  // Engineering — SWE Lead (1)
  {
    _idx: 20,
    id: '{{uuid_emp_20}}',
    organization_id: '{{ORG_ID}}',
    employee_number: 'MS-020',
    first_name: 'Michael',
    last_name: 'Hartmann',
    email: 'michael.hartmann@mueller-schmidt.de',
    gender: 'male',
    birth_year: 1981,
    job_profile_id: '{{uuid_jp_swe}}',
    job_level_id: '{{uuid_lvl_lead}}',
    department_id: '{{uuid_dept_eng}}',
    employment_type: 'full_time',
    location: 'Berlin',
    hire_date: '2017-06-01',
    base_salary: 110000,
    variable_pay: 8000,
    pay_band_id: '{{uuid_pb_swe_lead}}',
    _note: 'CTO / Tech Lead.',
  },
  // Engineering — DevOps (2)
  {
    _idx: 21,
    id: '{{uuid_emp_21}}',
    organization_id: '{{ORG_ID}}',
    employee_number: 'MS-021',
    first_name: 'Patrick',
    last_name: 'Lindner',
    email: 'patrick.lindner@mueller-schmidt.de',
    gender: 'male',
    birth_year: 1987,
    job_profile_id: '{{uuid_jp_devops}}',
    job_level_id: '{{uuid_lvl_senior}}',
    department_id: '{{uuid_dept_eng}}',
    employment_type: 'full_time',
    location: 'Berlin',
    hire_date: '2019-08-12',
    base_salary: 92000,
    pay_band_id: '{{uuid_pb_devops_sr}}',
  },
  {
    _idx: 22,
    id: '{{uuid_emp_22}}',
    organization_id: '{{ORG_ID}}',
    employee_number: 'MS-022',
    first_name: 'Carina',
    last_name: 'Roth',
    email: 'carina.roth@mueller-schmidt.de',
    gender: 'female',
    birth_year: 1990,
    job_profile_id: '{{uuid_jp_devops}}',
    job_level_id: '{{uuid_lvl_mid}}',
    department_id: '{{uuid_dept_eng}}',
    employment_type: 'full_time',
    location: 'München',
    hire_date: '2022-03-15',
    base_salary: 74000,
    pay_band_id: '{{uuid_pb_devops_mid}}',
  },
  // Engineering — PMs (2)
  {
    _idx: 23,
    id: '{{uuid_emp_23}}',
    organization_id: '{{ORG_ID}}',
    employee_number: 'MS-023',
    first_name: 'Elena',
    last_name: 'Friedrich',
    email: 'elena.friedrich@mueller-schmidt.de',
    gender: 'female',
    birth_year: 1985,
    job_profile_id: '{{uuid_jp_pm}}',
    job_level_id: '{{uuid_lvl_principal}}',
    department_id: '{{uuid_dept_eng}}',
    employment_type: 'full_time',
    location: 'Berlin',
    hire_date: '2018-02-01',
    base_salary: 128000,
    variable_pay: 10000,
    pay_band_id: '{{uuid_pb_pm_principal}}',
    _note: 'VP Product.',
  },
  {
    _idx: 24,
    id: '{{uuid_emp_24}}',
    organization_id: '{{ORG_ID}}',
    employee_number: 'MS-024',
    first_name: 'Jonas',
    last_name: 'Brandt',
    email: 'jonas.brandt@mueller-schmidt.de',
    gender: 'male',
    birth_year: 1988,
    job_profile_id: '{{uuid_jp_pm}}',
    job_level_id: '{{uuid_lvl_senior}}',
    department_id: '{{uuid_dept_eng}}',
    employment_type: 'full_time',
    location: 'Berlin',
    hire_date: '2021-05-10',
    base_salary: 93000,
    variable_pay: 4000,
    pay_band_id: '{{uuid_pb_pm_sr}}',
  },
  // Engineering — QA (1, on parental leave to show that state)
  {
    _idx: 25,
    id: '{{uuid_emp_25}}',
    organization_id: '{{ORG_ID}}',
    employee_number: 'MS-025',
    first_name: 'Mira',
    last_name: 'Weiß',
    email: 'mira.weiss@mueller-schmidt.de',
    gender: 'female',
    birth_year: 1993,
    job_profile_id: '{{uuid_jp_qa}}',
    job_level_id: '{{uuid_lvl_mid}}',
    department_id: '{{uuid_dept_eng}}',
    employment_type: 'full_time',
    location: 'München',
    hire_date: '2021-09-01',
    base_salary: 62000,
    pay_band_id: '{{uuid_pb_qa_mid}}',
    on_leave: true,
    leave_type: 'parental',
    leave_start: '2025-11-01',
    leave_end: '2026-08-31',
    _note: 'Elternzeit — sichtbar im Pay-Equity-Filter "include_on_leave".',
  },

  // ── Vertrieb (10) — incl. GAP-GRUPPE B (Account Executive Mid) ──
  {
    _idx: 26,
    id: '{{uuid_emp_26}}',
    organization_id: '{{ORG_ID}}',
    employee_number: 'MS-026',
    first_name: 'David',
    last_name: 'Lehmann',
    email: 'david.lehmann@mueller-schmidt.de',
    gender: 'male',
    birth_year: 1989,
    job_profile_id: '{{uuid_jp_ae}}',
    job_level_id: '{{uuid_lvl_mid}}',
    department_id: '{{uuid_dept_sales}}',
    employment_type: 'full_time',
    location: 'München',
    hire_date: '2020-04-20',
    base_salary: 67000,
    variable_pay: 22000, // OTE
    pay_band_id: '{{uuid_pb_ae_mid}}',
    _note: 'GAP-GRUPPE B · ♂',
  },
  {
    _idx: 27,
    id: '{{uuid_emp_27}}',
    organization_id: '{{ORG_ID}}',
    employee_number: 'MS-027',
    first_name: 'Florian',
    last_name: 'Beck',
    email: 'florian.beck@mueller-schmidt.de',
    gender: 'male',
    birth_year: 1991,
    job_profile_id: '{{uuid_jp_ae}}',
    job_level_id: '{{uuid_lvl_mid}}',
    department_id: '{{uuid_dept_sales}}',
    employment_type: 'full_time',
    location: 'München',
    hire_date: '2021-09-06',
    base_salary: 65000,
    variable_pay: 20000,
    pay_band_id: '{{uuid_pb_ae_mid}}',
    _note: 'GAP-GRUPPE B · ♂',
  },
  {
    _idx: 28,
    id: '{{uuid_emp_28}}',
    organization_id: '{{ORG_ID}}',
    employee_number: 'MS-028',
    first_name: 'Sebastian',
    last_name: 'Roth',
    email: 'sebastian.roth@mueller-schmidt.de',
    gender: 'male',
    birth_year: 1990,
    job_profile_id: '{{uuid_jp_ae}}',
    job_level_id: '{{uuid_lvl_mid}}',
    department_id: '{{uuid_dept_sales}}',
    employment_type: 'full_time',
    location: 'München',
    hire_date: '2022-01-15',
    base_salary: 66000,
    variable_pay: 21000,
    pay_band_id: '{{uuid_pb_ae_mid}}',
    _note: 'GAP-GRUPPE B · ♂',
  },
  {
    _idx: 29,
    id: '{{uuid_emp_29}}',
    organization_id: '{{ORG_ID}}',
    employee_number: 'MS-029',
    first_name: 'Marie',
    last_name: 'Köhler',
    email: 'marie.koehler@mueller-schmidt.de',
    gender: 'female',
    birth_year: 1992,
    job_profile_id: '{{uuid_jp_ae}}',
    job_level_id: '{{uuid_lvl_mid}}',
    department_id: '{{uuid_dept_sales}}',
    employment_type: 'full_time',
    location: 'München',
    hire_date: '2022-07-01',
    base_salary: 58500,
    variable_pay: 19000,
    pay_band_id: '{{uuid_pb_ae_mid}}',
    _note: 'GAP-GRUPPE B · ♀ — beantwortete info_request (info_requests #2).',
  },
  {
    _idx: 30,
    id: '{{uuid_emp_30}}',
    organization_id: '{{ORG_ID}}',
    employee_number: 'MS-030',
    first_name: 'Nicole',
    last_name: 'Schäfer',
    email: 'nicole.schaefer@mueller-schmidt.de',
    gender: 'female',
    birth_year: 1993,
    job_profile_id: '{{uuid_jp_ae}}',
    job_level_id: '{{uuid_lvl_mid}}',
    department_id: '{{uuid_dept_sales}}',
    employment_type: 'full_time',
    location: 'München',
    hire_date: '2023-03-13',
    base_salary: 57500,
    variable_pay: 18500,
    pay_band_id: '{{uuid_pb_ae_mid}}',
    _note: 'GAP-GRUPPE B · ♀',
  },
  // AE Senior (2 — clean cohort)
  {
    _idx: 31,
    id: '{{uuid_emp_31}}',
    organization_id: '{{ORG_ID}}',
    employee_number: 'MS-031',
    first_name: 'Robert',
    last_name: 'Engel',
    email: 'robert.engel@mueller-schmidt.de',
    gender: 'male',
    birth_year: 1984,
    job_profile_id: '{{uuid_jp_ae}}',
    job_level_id: '{{uuid_lvl_senior}}',
    department_id: '{{uuid_dept_sales}}',
    employment_type: 'full_time',
    location: 'München',
    hire_date: '2018-08-01',
    base_salary: 84000,
    variable_pay: 35000,
    pay_band_id: '{{uuid_pb_ae_sr}}',
    _note: 'Clean cohort AE-Senior (gap <2%).',
  },
  {
    _idx: 32,
    id: '{{uuid_emp_32}}',
    organization_id: '{{ORG_ID}}',
    employee_number: 'MS-032',
    first_name: 'Stefanie',
    last_name: 'Walter',
    email: 'stefanie.walter@mueller-schmidt.de',
    gender: 'female',
    birth_year: 1986,
    job_profile_id: '{{uuid_jp_ae}}',
    job_level_id: '{{uuid_lvl_senior}}',
    department_id: '{{uuid_dept_sales}}',
    employment_type: 'full_time',
    location: 'München',
    hire_date: '2019-02-04',
    base_salary: 83000,
    variable_pay: 34000,
    pay_band_id: '{{uuid_pb_ae_sr}}',
  },
  // SDR (3)
  {
    _idx: 33,
    id: '{{uuid_emp_33}}',
    organization_id: '{{ORG_ID}}',
    employee_number: 'MS-033',
    first_name: 'Kevin',
    last_name: 'Sommer',
    email: 'kevin.sommer@mueller-schmidt.de',
    gender: 'male',
    birth_year: 1997,
    job_profile_id: '{{uuid_jp_sdr}}',
    job_level_id: '{{uuid_lvl_junior}}',
    department_id: '{{uuid_dept_sales}}',
    employment_type: 'full_time',
    location: 'München',
    hire_date: '2024-03-04',
    base_salary: 46000,
    variable_pay: 12000,
    pay_band_id: '{{uuid_pb_sdr_jr}}',
  },
  {
    _idx: 34,
    id: '{{uuid_emp_34}}',
    organization_id: '{{ORG_ID}}',
    employee_number: 'MS-034',
    first_name: 'Anja',
    last_name: 'Krämer',
    email: 'anja.kraemer@mueller-schmidt.de',
    gender: 'female',
    birth_year: 1998,
    job_profile_id: '{{uuid_jp_sdr}}',
    job_level_id: '{{uuid_lvl_junior}}',
    department_id: '{{uuid_dept_sales}}',
    employment_type: 'full_time',
    location: 'München',
    hire_date: '2024-04-15',
    base_salary: 47000,
    variable_pay: 12000,
    pay_band_id: '{{uuid_pb_sdr_jr}}',
    _note: 'Clean cohort SDR-Junior (♀ minimal über ♂).',
  },
  {
    _idx: 35,
    id: '{{uuid_emp_35}}',
    organization_id: '{{ORG_ID}}',
    employee_number: 'MS-035',
    first_name: 'Mehmet',
    last_name: 'Yıldız',
    email: 'mehmet.yildiz@mueller-schmidt.de',
    gender: 'male',
    birth_year: 1996,
    job_profile_id: '{{uuid_jp_sdr}}',
    job_level_id: '{{uuid_lvl_junior}}',
    department_id: '{{uuid_dept_sales}}',
    employment_type: 'full_time',
    location: 'Berlin',
    hire_date: '2025-02-03',
    base_salary: 45000,
    variable_pay: 12000,
    pay_band_id: '{{uuid_pb_sdr_jr}}',
  },

  // ── Marketing (6) ─────────────────────────────────────────
  {
    _idx: 36,
    id: '{{uuid_emp_36}}',
    organization_id: '{{ORG_ID}}',
    employee_number: 'MS-036',
    first_name: 'Christina',
    last_name: 'Hennig',
    email: 'christina.hennig@mueller-schmidt.de',
    gender: 'female',
    birth_year: 1983,
    job_profile_id: '{{uuid_jp_mkt_mgr}}',
    job_level_id: '{{uuid_lvl_senior}}',
    department_id: '{{uuid_dept_marketing}}',
    employment_type: 'full_time',
    location: 'Berlin',
    hire_date: '2019-01-07',
    base_salary: 82000,
    variable_pay: 5000,
    pay_band_id: '{{uuid_pb_mkt_sr}}',
    _note: 'Head of Marketing.',
  },
  {
    _idx: 37,
    id: '{{uuid_emp_37}}',
    organization_id: '{{ORG_ID}}',
    employee_number: 'MS-037',
    first_name: 'Tim',
    last_name: 'Sauer',
    email: 'tim.sauer@mueller-schmidt.de',
    gender: 'male',
    birth_year: 1989,
    job_profile_id: '{{uuid_jp_mkt_mgr}}',
    job_level_id: '{{uuid_lvl_mid}}',
    department_id: '{{uuid_dept_marketing}}',
    employment_type: 'full_time',
    location: 'Berlin',
    hire_date: '2022-11-01',
    base_salary: 63000,
    pay_band_id: '{{uuid_pb_mkt_mid}}',
  },
  {
    _idx: 38,
    id: '{{uuid_emp_38}}',
    organization_id: '{{ORG_ID}}',
    employee_number: 'MS-038',
    first_name: 'Lisa',
    last_name: 'Berger',
    email: 'lisa.berger@mueller-schmidt.de',
    gender: 'female',
    birth_year: 1991,
    job_profile_id: '{{uuid_jp_mkt_mgr}}',
    job_level_id: '{{uuid_lvl_mid}}',
    department_id: '{{uuid_dept_marketing}}',
    employment_type: 'full_time',
    location: 'Berlin',
    hire_date: '2023-03-15',
    base_salary: 62500,
    pay_band_id: '{{uuid_pb_mkt_mid}}',
    _note: 'Clean cohort Marketing-Mid (♀ minimal unter ♂, <1% gap).',
  },
  {
    _idx: 39,
    id: '{{uuid_emp_39}}',
    organization_id: '{{ORG_ID}}',
    employee_number: 'MS-039',
    first_name: 'Maximilian',
    last_name: 'Otto',
    email: 'maximilian.otto@mueller-schmidt.de',
    gender: 'male',
    birth_year: 1996,
    job_profile_id: '{{uuid_jp_content}}',
    job_level_id: '{{uuid_lvl_junior}}',
    department_id: '{{uuid_dept_marketing}}',
    employment_type: 'full_time',
    location: 'Berlin',
    hire_date: '2023-09-12',
    base_salary: 46000,
    pay_band_id: '{{uuid_pb_content_jr}}',
  },
  {
    _idx: 40,
    id: '{{uuid_emp_40}}',
    organization_id: '{{ORG_ID}}',
    employee_number: 'MS-040',
    first_name: 'Sophie',
    last_name: 'Fuchs',
    email: 'sophie.fuchs@mueller-schmidt.de',
    gender: 'female',
    birth_year: 1997,
    job_profile_id: '{{uuid_jp_content}}',
    job_level_id: '{{uuid_lvl_junior}}',
    department_id: '{{uuid_dept_marketing}}',
    employment_type: 'full_time',
    location: 'Berlin',
    hire_date: '2024-05-02',
    base_salary: 46500,
    pay_band_id: '{{uuid_pb_content_jr}}',
  },
  {
    _idx: 41,
    id: '{{uuid_emp_41}}',
    organization_id: '{{ORG_ID}}',
    employee_number: 'MS-041',
    first_name: 'Hannah',
    last_name: 'Voß',
    email: 'hannah.voss@mueller-schmidt.de',
    gender: 'female',
    birth_year: 1994,
    job_profile_id: '{{uuid_jp_content}}',
    job_level_id: '{{uuid_lvl_junior}}',
    department_id: '{{uuid_dept_marketing}}',
    employment_type: 'part_time',
    weekly_hours: 32,
    location: 'Berlin',
    hire_date: '2024-08-19',
    base_salary: 37000, // pro-rata 32h
    pay_band_id: '{{uuid_pb_content_jr}}',
  },

  // ── Finanzen (6) ──────────────────────────────────────────
  {
    _idx: 42,
    id: '{{uuid_emp_42}}',
    organization_id: '{{ORG_ID}}',
    employee_number: 'MS-042',
    first_name: 'Andreas',
    last_name: 'Berger',
    email: 'andreas.berger@mueller-schmidt.de',
    gender: 'male',
    birth_year: 1979,
    job_profile_id: '{{uuid_jp_controller}}',
    job_level_id: '{{uuid_lvl_senior}}',
    department_id: '{{uuid_dept_finance}}',
    employment_type: 'full_time',
    location: 'Berlin',
    hire_date: '2017-03-01',
    base_salary: 88000,
    pay_band_id: '{{uuid_pb_controller_sr}}',
    _note: 'CFO-Stellvertretung.',
  },
  {
    _idx: 43,
    id: '{{uuid_emp_43}}',
    organization_id: '{{ORG_ID}}',
    employee_number: 'MS-043',
    first_name: 'Tanja',
    last_name: 'Pohl',
    email: 'tanja.pohl@mueller-schmidt.de',
    gender: 'female',
    birth_year: 1986,
    job_profile_id: '{{uuid_jp_controller}}',
    job_level_id: '{{uuid_lvl_mid}}',
    department_id: '{{uuid_dept_finance}}',
    employment_type: 'full_time',
    location: 'Berlin',
    hire_date: '2020-11-02',
    base_salary: 68000,
    pay_band_id: '{{uuid_pb_controller_mid}}',
  },
  {
    _idx: 44,
    id: '{{uuid_emp_44}}',
    organization_id: '{{ORG_ID}}',
    employee_number: 'MS-044',
    first_name: 'Bernd',
    last_name: 'Keller',
    email: 'bernd.keller@mueller-schmidt.de',
    gender: 'male',
    birth_year: 1975,
    job_profile_id: '{{uuid_jp_accountant}}',
    job_level_id: '{{uuid_lvl_mid}}',
    department_id: '{{uuid_dept_finance}}',
    employment_type: 'full_time',
    location: 'Berlin',
    hire_date: '2016-06-01',
    base_salary: 60000,
    pay_band_id: '{{uuid_pb_accountant_mid}}',
  },
  {
    _idx: 45,
    id: '{{uuid_emp_45}}',
    organization_id: '{{ORG_ID}}',
    employee_number: 'MS-045',
    first_name: 'Heike',
    last_name: 'Lorenz',
    email: 'heike.lorenz@mueller-schmidt.de',
    gender: 'female',
    birth_year: 1978,
    job_profile_id: '{{uuid_jp_accountant}}',
    job_level_id: '{{uuid_lvl_mid}}',
    department_id: '{{uuid_dept_finance}}',
    employment_type: 'full_time',
    location: 'Berlin',
    hire_date: '2018-09-10',
    base_salary: 59500,
    pay_band_id: '{{uuid_pb_accountant_mid}}',
    _note: 'Clean cohort Buchhaltung-Mid (gap <1%).',
  },
] as const;

// ─────────────────────────────────────────────────────────────────────────────
// 7. SALARY DECISIONS  (25 — spread over 24 months)
// ─────────────────────────────────────────────────────────────────────────────
//   types:  10 hire  ·  10 raise  ·  3 promotion  ·  2 band_change
//   decided_by_user_id = {{OWNER_USER}}  (Sandra Becker, HR Lead)

export const salaryDecisions = [
  // ── 10 × HIRE ────────────────────────────────────────────
  {
    id: '{{uuid_sd_01}}',
    organization_id: '{{ORG_ID}}',
    employee_id: '{{uuid_emp_07}}', // Sabrina Maier
    decision_type: 'hire',
    old_salary: null,
    new_salary: 42000,
    justification_text:
      'Einstieg als Office Manager Junior. Vergütung gemäß Pay Band Junior Mid-Range. Vorerfahrung 1 Jahr im Office-Management-Bereich, keine Führungsverantwortung — daher Mid-Range statt obere Range.',
    justification_factors: ['seniority', 'market_benchmark', 'role_responsibility'],
    decided_at: '2024-01-15T09:30:00Z',
    pay_band_id: '{{uuid_pb_office_jr}}',
    comparator_data: { band_min: 38000, band_median: 43000, band_max: 48000, peer_count_same_band: 4 },
  },
  {
    id: '{{uuid_sd_02}}',
    organization_id: '{{ORG_ID}}',
    employee_id: '{{uuid_emp_18}}', // Pauline Krause (SWE Jr)
    decision_type: 'hire',
    old_salary: null,
    new_salary: 52000,
    justification_text:
      'Einstellung Software Engineer Junior. Oberhalb Pay-Band-Median wegen abgeschlossenem Master-Abschluss Informatik und 2 vorhergehender Praktika bei namhaften SaaS-Firmen. Marktanpassung gemäß Stepstone-Benchmark Tech Berlin 2024.',
    justification_factors: ['education', 'prior_experience', 'market_benchmark'],
    decided_at: '2024-09-01T10:00:00Z',
    pay_band_id: '{{uuid_pb_swe_jr}}',
    comparator_data: { band_min: 48000, band_median: 53000, band_max: 58000, peer_count_same_band: 1 },
  },
  {
    id: '{{uuid_sd_03}}',
    organization_id: '{{ORG_ID}}',
    employee_id: '{{uuid_emp_19}}', // Niklas Schreiber
    decision_type: 'hire',
    old_salary: null,
    new_salary: 51000,
    justification_text:
      'Einstellung Software Engineer Junior. Gleicher Einstiegslevel wie Vergleichsperson, leicht unterhalb Median wegen geringerer Vorerfahrung (1 Werkstudent-Stelle). Pay Band Junior Lower-Mid.',
    justification_factors: ['prior_experience', 'market_benchmark'],
    decided_at: '2025-01-13T09:15:00Z',
    pay_band_id: '{{uuid_pb_swe_jr}}',
    comparator_data: { band_min: 48000, band_median: 53000, band_max: 58000, peer_count_same_band: 2 },
  },
  {
    id: '{{uuid_sd_04}}',
    organization_id: '{{ORG_ID}}',
    employee_id: '{{uuid_emp_33}}', // Kevin Sommer (SDR)
    decision_type: 'hire',
    old_salary: null,
    new_salary: 46000,
    justification_text:
      'Einstellung SDR Junior. Pay Band Junior Mid-Range. OTE 58.000 EUR (Base 46k + 12k Variable). Quereinsteiger aus Hotellerie, starke Kommunikationsfähigkeit.',
    justification_factors: ['market_benchmark', 'role_responsibility'],
    decided_at: '2024-03-04T11:00:00Z',
    pay_band_id: '{{uuid_pb_sdr_jr}}',
    comparator_data: { band_min: 42000, band_median: 47000, band_max: 52000, peer_count_same_band: 0 },
  },
  {
    id: '{{uuid_sd_05}}',
    organization_id: '{{ORG_ID}}',
    employee_id: '{{uuid_emp_34}}', // Anja Krämer (SDR)
    decision_type: 'hire',
    old_salary: null,
    new_salary: 47000,
    justification_text:
      'Einstellung SDR Junior. Gleiche Rolle wie Vergleichsperson MS-033, leicht über Median wegen abgeschlossenem Bachelor BWL + erstem 1-Jahres-Sales-Job. OTE 59k.',
    justification_factors: ['education', 'prior_experience', 'market_benchmark'],
    decided_at: '2024-04-15T14:00:00Z',
    pay_band_id: '{{uuid_pb_sdr_jr}}',
    comparator_data: { band_min: 42000, band_median: 47000, band_max: 52000, peer_count_same_band: 1 },
  },
  {
    id: '{{uuid_sd_06}}',
    organization_id: '{{ORG_ID}}',
    employee_id: '{{uuid_emp_29}}', // Marie Köhler (AE Mid)  — GAP-GRUPPE B
    decision_type: 'hire',
    old_salary: null,
    new_salary: 58500,
    justification_text:
      'Einstellung Account Executive Mid. 3 Jahre Vorerfahrung im B2B SaaS Vertrieb, kein eigener Buchclose-Track-Record. Pay Band Mid Lower-Range. OTE 77.500 EUR.',
    justification_factors: ['prior_experience', 'role_responsibility', 'market_benchmark'],
    decided_at: '2022-07-01T10:00:00Z',
    pay_band_id: '{{uuid_pb_ae_mid}}',
    comparator_data: { band_min: 52000, band_median: 62000, band_max: 72000, peer_count_same_band: 3 },
    _note: 'Wird durch Pay-Equity-View geflagged — wir prüfen ob Begründung trägt.',
  },
  {
    id: '{{uuid_sd_07}}',
    organization_id: '{{ORG_ID}}',
    employee_id: '{{uuid_emp_30}}', // Nicole Schäfer (AE Mid) — GAP-GRUPPE B
    decision_type: 'hire',
    old_salary: null,
    new_salary: 57500,
    justification_text:
      'Einstellung Account Executive Mid. Quereinsteigerin aus Inside Sales, 2 Jahre Erfahrung. Pay Band Mid Lower-Range. OTE 76.000 EUR.',
    justification_factors: ['prior_experience', 'market_benchmark'],
    decided_at: '2023-03-13T09:30:00Z',
    pay_band_id: '{{uuid_pb_ae_mid}}',
    comparator_data: { band_min: 52000, band_median: 62000, band_max: 72000, peer_count_same_band: 4 },
    _note: 'Trägt zur Gap in Gruppe B bei — Demoeffekt: Lücke ist VOR Justification entstanden.',
  },
  {
    id: '{{uuid_sd_08}}',
    organization_id: '{{ORG_ID}}',
    employee_id: '{{uuid_emp_14}}', // Julia Richter (SWE Sr) — GAP-GRUPPE A
    decision_type: 'hire',
    old_salary: null,
    new_salary: 73000,
    justification_text:
      'Einstellung Software Engineer auf Senior-Level via internem Performance-Path. Externer Wechsel mit 4 Jahren Vorerfahrung. Pay Band Senior Lower-Range, da kein vorheriger Tech-Lead-Track-Record.',
    justification_factors: ['prior_experience', 'market_benchmark'],
    decided_at: '2022-01-10T10:00:00Z',
    pay_band_id: '{{uuid_pb_swe_sr}}',
    comparator_data: { band_min: 75000, band_median: 85000, band_max: 95000, peer_count_same_band: 5 },
    _note: 'Einstieg unter Pay-Band-Minimum (Ausnahme dokumentiert) — wird heute korrigiert (siehe sd_24).',
  },
  {
    id: '{{uuid_sd_09}}',
    organization_id: '{{ORG_ID}}',
    employee_id: '{{uuid_emp_40}}', // Sophie Fuchs (Content Jr)
    decision_type: 'hire',
    old_salary: null,
    new_salary: 46500,
    justification_text:
      'Einstellung Content Specialist Junior. Pay Band Junior Mid-Range. Frische Absolventin Kommunikationswissenschaft mit Praktika bei zwei Verlagen.',
    justification_factors: ['education', 'prior_experience', 'market_benchmark'],
    decided_at: '2024-05-02T10:00:00Z',
    pay_band_id: '{{uuid_pb_content_jr}}',
    comparator_data: { band_min: 42000, band_median: 47000, band_max: 52000, peer_count_same_band: 1 },
  },
  {
    id: '{{uuid_sd_10}}',
    organization_id: '{{ORG_ID}}',
    employee_id: '{{uuid_emp_35}}', // Mehmet Yıldız (SDR)
    decision_type: 'hire',
    old_salary: null,
    new_salary: 45000,
    justification_text:
      'Einstellung SDR Junior. Pay Band Junior Lower-Range. Keine spezifische Sales-Vorerfahrung, aber 2 Jahre Customer-Success-Tätigkeit. OTE 57.000 EUR.',
    justification_factors: ['prior_experience', 'market_benchmark'],
    decided_at: '2025-02-03T11:00:00Z',
    pay_band_id: '{{uuid_pb_sdr_jr}}',
    comparator_data: { band_min: 42000, band_median: 47000, band_max: 52000, peer_count_same_band: 2 },
  },

  // ── 10 × RAISE ───────────────────────────────────────────
  {
    id: '{{uuid_sd_11}}',
    organization_id: '{{ORG_ID}}',
    employee_id: '{{uuid_emp_08}}', // Lukas Bauer (SWE Sr — GAP A ♂)
    decision_type: 'raise',
    old_salary: 86000,
    new_salary: 90000,
    justification_text:
      'Jährliche Gehaltsanpassung 2026. Performance Review Note "übertrifft Erwartungen" (4.5/5). Marktanpassung gemäß Stepstone-Benchmark Tech Senior Berlin +4,6%.',
    justification_factors: ['performance_rating', 'market_benchmark', 'tenure'],
    decided_at: '2026-01-15T10:00:00Z',
    pay_band_id: '{{uuid_pb_swe_sr}}',
    comparator_data: { band_min: 75000, band_median: 85000, band_max: 95000, peer_count_same_band: 7 },
  },
  {
    id: '{{uuid_sd_12}}',
    organization_id: '{{ORG_ID}}',
    employee_id: '{{uuid_emp_10}}', // Stefan Wagner (SWE Sr — GAP A ♂)
    decision_type: 'raise',
    old_salary: 84500,
    new_salary: 89000,
    justification_text:
      'Jährliche Gehaltsanpassung 2026. Performance Review Note "übertrifft Erwartungen". Längste Betriebszugehörigkeit im Senior-Pool, Mentoring-Rolle für 2 Mids.',
    justification_factors: ['performance_rating', 'tenure', 'role_responsibility'],
    decided_at: '2026-01-15T10:00:00Z',
    pay_band_id: '{{uuid_pb_swe_sr}}',
    comparator_data: { band_min: 75000, band_median: 85000, band_max: 95000, peer_count_same_band: 7 },
  },
  {
    id: '{{uuid_sd_13}}',
    organization_id: '{{ORG_ID}}',
    employee_id: '{{uuid_emp_13}}', // Lena Hofmann (SWE Sr — GAP A ♀)
    decision_type: 'raise',
    old_salary: 76000,
    new_salary: 79000,
    justification_text:
      'Jährliche Gehaltsanpassung 2026. Performance Review Note "erfüllt Erwartungen" (3.5/5). Inflationsausgleich + 3.9%.',
    justification_factors: ['performance_rating', 'cost_of_living'],
    decided_at: '2026-01-15T10:00:00Z',
    pay_band_id: '{{uuid_pb_swe_sr}}',
    comparator_data: { band_min: 75000, band_median: 85000, band_max: 95000, peer_count_same_band: 7 },
    _note: 'Demoeffekt: zeigt dass Steigerungen pro Jahr ähnlich, aber Startgehalt asymmetrisch — Gap entsteht aus Hire-Zeitpunkt.',
  },
  {
    id: '{{uuid_sd_14}}',
    organization_id: '{{ORG_ID}}',
    employee_id: '{{uuid_emp_12}}', // Anna Schulz (SWE Sr — GAP A ♀)
    decision_type: 'raise',
    old_salary: 77000,
    new_salary: 80000,
    justification_text:
      'Jährliche Gehaltsanpassung 2026. Performance Review Note "erfüllt Erwartungen". Marktanpassung +3,9%, gleicher Prozentsatz wie Vergleichsperson MS-013.',
    justification_factors: ['performance_rating', 'cost_of_living', 'market_benchmark'],
    decided_at: '2026-01-15T10:00:00Z',
    pay_band_id: '{{uuid_pb_swe_sr}}',
    comparator_data: { band_min: 75000, band_median: 85000, band_max: 95000, peer_count_same_band: 7 },
  },
  {
    id: '{{uuid_sd_15}}',
    organization_id: '{{ORG_ID}}',
    employee_id: '{{uuid_emp_21}}', // Patrick Lindner (DevOps Sr)
    decision_type: 'raise',
    old_salary: 88000,
    new_salary: 92000,
    justification_text:
      'Jährliche Gehaltsanpassung 2026. Performance Review Note "übertrifft Erwartungen". On-Call-Verantwortung übernommen, AWS Solutions Architect Cert erworben.',
    justification_factors: ['performance_rating', 'certification', 'role_responsibility'],
    decided_at: '2026-01-15T10:00:00Z',
    pay_band_id: '{{uuid_pb_devops_sr}}',
    comparator_data: { band_min: 80000, band_median: 90000, band_max: 100000, peer_count_same_band: 1 },
  },
  {
    id: '{{uuid_sd_16}}',
    organization_id: '{{ORG_ID}}',
    employee_id: '{{uuid_emp_26}}', // David Lehmann (AE Mid — GAP B ♂)
    decision_type: 'raise',
    old_salary: 64000,
    new_salary: 67000,
    justification_text:
      'Jährliche Gehaltsanpassung 2026. Performance Review Note "erfüllt Erwartungen", Quota-Achievement 105%. Marktanpassung +4,7%.',
    justification_factors: ['performance_rating', 'quota_achievement', 'market_benchmark'],
    decided_at: '2026-01-15T10:00:00Z',
    pay_band_id: '{{uuid_pb_ae_mid}}',
    comparator_data: { band_min: 52000, band_median: 62000, band_max: 72000, peer_count_same_band: 5 },
  },
  {
    id: '{{uuid_sd_17}}',
    organization_id: '{{ORG_ID}}',
    employee_id: '{{uuid_emp_29}}', // Marie Köhler (AE Mid — GAP B ♀)
    decision_type: 'raise',
    old_salary: 56500,
    new_salary: 58500,
    justification_text:
      'Jährliche Gehaltsanpassung 2026. Performance Review Note "erfüllt Erwartungen", Quota-Achievement 98%. Inflationsausgleich + 3,5%.',
    justification_factors: ['performance_rating', 'quota_achievement', 'cost_of_living'],
    decided_at: '2026-01-15T10:00:00Z',
    pay_band_id: '{{uuid_pb_ae_mid}}',
    comparator_data: { band_min: 52000, band_median: 62000, band_max: 72000, peer_count_same_band: 5 },
    _note: 'Demoeffekt: gleicher Begründungstyp, niedrigere %-Steigerung — Anlass zur Diskussion in Beweislastumkehr-Szenario.',
  },
  {
    id: '{{uuid_sd_18}}',
    organization_id: '{{ORG_ID}}',
    employee_id: '{{uuid_emp_42}}', // Andreas Berger (Controller Sr)
    decision_type: 'raise',
    old_salary: 84500,
    new_salary: 88000,
    justification_text:
      'Jährliche Gehaltsanpassung 2026. Performance Review Note "übertrifft Erwartungen". Übernahme stellvertretender CFO-Rolle in Q4/2025.',
    justification_factors: ['performance_rating', 'role_responsibility', 'tenure'],
    decided_at: '2026-01-15T10:00:00Z',
    pay_band_id: '{{uuid_pb_controller_sr}}',
    comparator_data: { band_min: 78000, band_median: 88000, band_max: 98000, peer_count_same_band: 1 },
  },
  {
    id: '{{uuid_sd_19}}',
    organization_id: '{{ORG_ID}}',
    employee_id: '{{uuid_emp_36}}', // Christina Hennig (Marketing Sr)
    decision_type: 'raise',
    old_salary: 78500,
    new_salary: 82000,
    justification_text:
      'Jährliche Gehaltsanpassung 2026. Performance Review Note "übertrifft Erwartungen". Pipeline-Beitrag +18%, Hire eines Mid-Marketers begleitet.',
    justification_factors: ['performance_rating', 'role_responsibility', 'market_benchmark'],
    decided_at: '2026-01-15T10:00:00Z',
    pay_band_id: '{{uuid_pb_mkt_sr}}',
    comparator_data: { band_min: 72000, band_median: 82000, band_max: 92000, peer_count_same_band: 1 },
  },
  {
    id: '{{uuid_sd_20}}',
    organization_id: '{{ORG_ID}}',
    employee_id: '{{uuid_emp_22}}', // Carina Roth (DevOps Mid)
    decision_type: 'raise',
    old_salary: 70000,
    new_salary: 74000,
    justification_text:
      'Außerplanmäßige Anpassung Q3/2025. Retentions-Maßnahme nach Wettbewerbsangebot. Marktbenchmark (Glassdoor + Stepstone) bestätigt 74k als Median für vergleichbare Rolle in München.',
    justification_factors: ['retention_risk', 'market_benchmark'],
    decided_at: '2025-09-20T15:30:00Z',
    pay_band_id: '{{uuid_pb_devops_mid}}',
    comparator_data: { band_min: 65000, band_median: 74000, band_max: 82000, peer_count_same_band: 0 },
  },

  // ── 3 × PROMOTION ────────────────────────────────────────
  {
    id: '{{uuid_sd_21}}',
    organization_id: '{{ORG_ID}}',
    employee_id: '{{uuid_emp_11}}', // Christian Vogel (SWE → Senior in 2024)
    decision_type: 'promotion',
    old_salary: 72000,
    new_salary: 84000,
    justification_text:
      'Beförderung Mid → Senior nach 30 Monaten. Tech-Lead-Rolle in einem Crossfunctional-Team übernommen, technische Strategie für Migrationsprojekt verantwortet. Pay-Band-Anpassung auf Senior Mid-Range.',
    justification_factors: ['role_responsibility', 'performance_rating', 'tenure'],
    decided_at: '2024-04-01T10:00:00Z',
    pay_band_id: '{{uuid_pb_swe_sr}}',
    comparator_data: { band_min: 75000, band_median: 85000, band_max: 95000, peer_count_same_band: 6 },
  },
  {
    id: '{{uuid_sd_22}}',
    organization_id: '{{ORG_ID}}',
    employee_id: '{{uuid_emp_24}}', // Jonas Brandt (PM → Senior in 2024)
    decision_type: 'promotion',
    old_salary: 78000,
    new_salary: 90000,
    justification_text:
      'Beförderung Mid → Senior Product Manager nach 33 Monaten. Eigenständige Verantwortung für Produktlinie übernommen. KPIs erfüllt (NPS +12, Activation +8%).',
    justification_factors: ['role_responsibility', 'performance_rating', 'kpi_achievement'],
    decided_at: '2024-02-15T10:00:00Z',
    pay_band_id: '{{uuid_pb_pm_sr}}',
    comparator_data: { band_min: 82000, band_median: 92000, band_max: 102000, peer_count_same_band: 0 },
  },
  {
    id: '{{uuid_sd_23}}',
    organization_id: '{{ORG_ID}}',
    employee_id: '{{uuid_emp_01}}', // Sandra Becker (HRBP Sr → Lead)
    decision_type: 'promotion',
    old_salary: 88000,
    new_salary: 100000,
    justification_text:
      'Beförderung HR Business Partner Senior → Lead. Übernahme Team-Lead-Verantwortung für gesamtes HR-Team (3 Personen), Eigenverantwortung Compensation-Strategy 2025/26.',
    justification_factors: ['role_responsibility', 'team_size', 'strategic_scope'],
    decided_at: '2024-01-01T09:00:00Z',
    pay_band_id: '{{uuid_pb_hrbp_lead}}',
    comparator_data: { band_min: 92000, band_median: 104000, band_max: 115000, peer_count_same_band: 0 },
  },

  // ── 2 × BAND_CHANGE ──────────────────────────────────────
  {
    id: '{{uuid_sd_24}}',
    organization_id: '{{ORG_ID}}',
    employee_id: '{{uuid_emp_14}}', // Julia Richter — initial hire war unter band, jetzt Korrektur
    decision_type: 'band_change',
    old_salary: 73000,
    new_salary: 76500,
    justification_text:
      'Pay-Band-Anpassung auf Senior Lower-Range Minimum. Ursprüngliche Einstellung lag unter dem Senior-Minimum. Anpassung zum Halbjahres-Review 2025 nach Markt-Reset durch HR.',
    justification_factors: ['band_alignment', 'market_benchmark', 'correction'],
    decided_at: '2025-07-01T10:00:00Z',
    pay_band_id: '{{uuid_pb_swe_sr}}',
    comparator_data: { band_min: 75000, band_median: 85000, band_max: 95000, peer_count_same_band: 6 },
    _note: 'Demo-relevant: zeigt, dass System Band-Verstöße erkennt und HR aktiv nachbessert.',
  },
  {
    id: '{{uuid_sd_25}}',
    organization_id: '{{ORG_ID}}',
    employee_id: '{{uuid_emp_17}}', // Philipp Neumann (SWE Mid band reset)
    decision_type: 'band_change',
    old_salary: 68000,
    new_salary: 71000,
    justification_text:
      'Band-Anpassung nach jährlichem Pay-Band-Review 2026. Neuer Median für Software Engineer Mid auf 70.000 EUR angehoben (Stepstone-Benchmark Berlin Q4/2025). Personen unter neuem Mid-Median +3k angepasst.',
    justification_factors: ['band_alignment', 'market_benchmark'],
    decided_at: '2026-01-15T10:00:00Z',
    pay_band_id: '{{uuid_pb_swe_mid}}',
    comparator_data: { band_min: 62000, band_median: 70000, band_max: 78000, peer_count_same_band: 2 },
  },
] as const;

// ─────────────────────────────────────────────────────────────────────────────
// 8. INFO REQUESTS  (3 — open / fulfilled / overdue)
// ─────────────────────────────────────────────────────────────────────────────

export const infoRequests = [
  {
    id: '{{uuid_ir_01}}',
    organization_id: '{{ORG_ID}}',
    employee_id: '{{uuid_emp_07}}', // Sabrina Maier (Office Jr)
    request_type: 'avg_pay_category',
    job_profile_id: '{{uuid_jp_office}}',
    status: 'pending',
    response_data: null,
    processed_by: null,
    processed_at: null,
    created_at: '2026-05-12T14:22:00Z',
    _question_de:
      'Ich möchte das durchschnittliche Entgelt für meine Vergleichsgruppe (Office & Operations Manager, Junior) aufgeschlüsselt nach Geschlecht erhalten.',
    _note: 'OFFEN — vor 2 Tagen submitted, noch keine Antwort. Live-Demo: HR-Lead beantwortet sie aus dem Pay-Equity-View.',
  },
  {
    id: '{{uuid_ir_02}}',
    organization_id: '{{ORG_ID}}',
    employee_id: '{{uuid_emp_29}}', // Marie Köhler (AE Mid — GAP B ♀)
    request_type: 'avg_pay_category',
    job_profile_id: '{{uuid_jp_ae}}',
    status: 'fulfilled',
    response_data: {
      job_profile: 'Account Executive',
      job_level: 'Mid',
      employee_count: 5,
      median_base_salary_eur: 65000,
      male_median_base_eur: 66000,
      female_median_base_eur: 58000,
      mean_gap_pct: 12.1,
      flagged: true,
      reply_text:
        'Vielen Dank für Ihre Anfrage. Die Vergleichsgruppe "Account Executive · Mid" umfasst 5 Beschäftigte. Median Basisgehalt insgesamt: 65.000 EUR. Aufgeschlüsselt nach Geschlecht: ♂ Median 66.000 EUR (3 Personen) · ♀ Median 58.000 EUR (2 Personen). Ein Lohnunterschied von mehr als 5% besteht und wird derzeit von der Personalleitung im Detail geprüft.',
    },
    processed_by: '{{OWNER_USER}}',
    processed_at: '2026-04-22T11:30:00Z',
    created_at: '2026-04-15T09:14:00Z',
    _question_de:
      'Bitte teilen Sie mir das durchschnittliche Entgelt für Account Executive Mid-Level nach Geschlecht mit.',
    _note: 'BEANTWORTET — 7 Tage Bearbeitungszeit, vollständige Aufschlüsselung inkl. Gap-Hinweis.',
  },
  {
    id: '{{uuid_ir_03}}',
    organization_id: '{{ORG_ID}}',
    employee_id: '{{uuid_emp_12}}', // Anna Schulz (SWE Sr — GAP A ♀)
    request_type: 'avg_pay_category',
    job_profile_id: '{{uuid_jp_swe}}',
    status: 'pending',
    response_data: null,
    processed_by: null,
    processed_at: null,
    created_at: '2026-04-25T08:45:00Z',
    _question_de:
      'Ich bitte gemäß §10 EntgTranspG (bzw. Art. 7 EU-Richtlinie 2023/970) um Auskunft über das durchschnittliche Entgelt für die Vergleichsgruppe "Software Engineer · Senior" — aufgeschlüsselt nach Geschlecht und einschließlich variabler Bestandteile.',
    _note:
      'ÜBERFÄLLIG — 19 Tage offen, noch keine Antwort. Sales-Pitch: "Hier sehen Sie, warum klargehalt einen Warning-Banner zeigt — Sie sind im Risiko."',
  },
] as const;

// ─────────────────────────────────────────────────────────────────────────────
// 9. AUDIT LOG  (10 entries — varied actions, recent 30 days)
// ─────────────────────────────────────────────────────────────────────────────

export const auditLogs = [
  {
    id: '{{uuid_audit_01}}',
    organization_id: '{{ORG_ID}}',
    user_id: '{{OWNER_USER}}',
    action: 'auth.login',
    entity_type: 'user',
    entity_id: null,
    before_state: null,
    after_state: { method: 'oidc', mfa: false },
    ip_address: '85.180.42.118',
    created_at: '2026-05-14T07:42:00Z',
  },
  {
    id: '{{uuid_audit_02}}',
    organization_id: '{{ORG_ID}}',
    user_id: '{{OWNER_USER}}',
    action: 'salary_decision.created',
    entity_type: 'salary_decision',
    entity_id: '{{uuid_sd_11}}',
    before_state: null,
    after_state: { decision_type: 'raise', employee_id: '{{uuid_emp_08}}', new_salary: 90000 },
    ip_address: '85.180.42.118',
    created_at: '2026-01-15T10:01:14Z',
  },
  {
    id: '{{uuid_audit_03}}',
    organization_id: '{{ORG_ID}}',
    user_id: '{{OWNER_USER}}',
    action: 'salary_decision.created',
    entity_type: 'salary_decision',
    entity_id: '{{uuid_sd_13}}',
    before_state: null,
    after_state: { decision_type: 'raise', employee_id: '{{uuid_emp_13}}', new_salary: 79000 },
    ip_address: '85.180.42.118',
    created_at: '2026-01-15T10:03:08Z',
  },
  {
    id: '{{uuid_audit_04}}',
    organization_id: '{{ORG_ID}}',
    user_id: '{{OWNER_USER}}',
    action: 'info_request.fulfilled',
    entity_type: 'info_request',
    entity_id: '{{uuid_ir_02}}',
    before_state: { status: 'pending' },
    after_state: { status: 'fulfilled', processed_at: '2026-04-22T11:30:00Z' },
    ip_address: '85.180.42.118',
    created_at: '2026-04-22T11:30:11Z',
  },
  {
    id: '{{uuid_audit_05}}',
    organization_id: '{{ORG_ID}}',
    user_id: '{{OWNER_USER}}',
    action: 'employee.created',
    entity_type: 'employee',
    entity_id: '{{uuid_emp_35}}',
    before_state: null,
    after_state: { first_name: 'Mehmet', last_name: 'Yıldız', job_level: 'Junior' },
    ip_address: '85.180.42.118',
    created_at: '2025-02-03T11:14:22Z',
  },
  {
    id: '{{uuid_audit_06}}',
    organization_id: '{{ORG_ID}}',
    user_id: '{{OWNER_USER}}',
    action: 'role.granted',
    entity_type: 'organization_member',
    entity_id: null,
    before_state: null,
    after_state: { user_id: '{{HR_USER}}', role: 'hr_manager' },
    ip_address: '85.180.42.118',
    created_at: '2024-11-12T09:25:00Z',
  },
  {
    id: '{{uuid_audit_07}}',
    organization_id: '{{ORG_ID}}',
    user_id: '{{HR_USER}}',
    action: 'auth.login',
    entity_type: 'user',
    entity_id: null,
    before_state: null,
    after_state: { method: 'oidc', mfa: false },
    ip_address: '91.42.18.203',
    created_at: '2026-05-13T08:14:00Z',
  },
  {
    id: '{{uuid_audit_08}}',
    organization_id: '{{ORG_ID}}',
    user_id: '{{OWNER_USER}}',
    action: 'pay_band.updated',
    entity_type: 'pay_band',
    entity_id: '{{uuid_pb_swe_mid}}',
    before_state: { min_salary: 60000, median: 68000, max_salary: 75000 },
    after_state: { min_salary: 62000, median: 70000, max_salary: 78000 },
    ip_address: '85.180.42.118',
    created_at: '2026-01-14T16:08:00Z',
  },
  {
    id: '{{uuid_audit_09}}',
    organization_id: '{{ORG_ID}}',
    user_id: '{{OWNER_USER}}',
    action: 'salary_decision.created',
    entity_type: 'salary_decision',
    entity_id: '{{uuid_sd_24}}',
    before_state: null,
    after_state: { decision_type: 'band_change', employee_id: '{{uuid_emp_14}}', new_salary: 76500 },
    ip_address: '85.180.42.118',
    created_at: '2025-07-01T10:02:33Z',
  },
  {
    id: '{{uuid_audit_10}}',
    organization_id: '{{ORG_ID}}',
    user_id: '{{OWNER_USER}}',
    action: 'job_posting.published',
    entity_type: 'job_posting',
    entity_id: '{{uuid_jpost_01}}',
    before_state: { status: 'draft' },
    after_state: { status: 'published', salary_range_min: 80000, salary_range_max: 100000 },
    ip_address: '85.180.42.118',
    created_at: '2026-05-08T13:42:00Z',
  },
] as const;

// ─────────────────────────────────────────────────────────────────────────────
// 10. JOB POSTINGS  (3 — 1 published, 1 draft, 1 closed)
// ─────────────────────────────────────────────────────────────────────────────

export const jobPostings = [
  {
    id: '{{uuid_jpost_01}}',
    organization_id: '{{ORG_ID}}',
    title: 'Senior Backend Engineer (m/w/d) · Berlin',
    job_profile_id: '{{uuid_jp_swe}}',
    job_level_id: '{{uuid_lvl_senior}}',
    department_id: '{{uuid_dept_eng}}',
    salary_range_min: 80000,
    salary_range_max: 100000,
    currency: 'EUR',
    location: 'Berlin (hybrid)',
    employment_type: 'full_time',
    status: 'published',
    salary_disclosed: true,
    published_at: '2026-05-08T13:42:00Z',
    closed_at: null,
    description:
      'Wir suchen einen erfahrenen Backend Engineer für unser Plattformteam in Berlin. TypeScript/Node.js, PostgreSQL, AWS. Hybrid (2 Tage Office), 30 Tage Urlaub, betriebliche Altersvorsorge.',
    export_text:
      'Gehaltsspanne: 80.000 – 100.000 EUR Brutto/Jahr (40h/Woche). Die finale Einstufung erfolgt anhand objektiver, geschlechtsneutraler Kriterien (Berufserfahrung, technische Expertise, Vorerfahrung in vergleichbarer Rolle). Wir beantworten Bewerbungsanfragen unabhängig vom Geschlecht.',
    created_by: '{{OWNER_USER}}',
    _note: 'Demo: zeigt Article-5-konforme Stellenanzeige mit offengelegter Spanne.',
  },
  {
    id: '{{uuid_jpost_02}}',
    organization_id: '{{ORG_ID}}',
    title: 'Account Executive Senior (m/w/d) · München',
    job_profile_id: '{{uuid_jp_ae}}',
    job_level_id: '{{uuid_lvl_senior}}',
    department_id: '{{uuid_dept_sales}}',
    salary_range_min: 75000,
    salary_range_max: 92000,
    currency: 'EUR',
    location: 'München (hybrid)',
    employment_type: 'full_time',
    status: 'draft',
    salary_disclosed: true,
    published_at: null,
    closed_at: null,
    description:
      'Account Executive Senior für DACH-Vertrieb. Vollverantwortung Pipeline + Closing. OTE 110–135k. Erfahrung B2B SaaS 5+ Jahre.',
    export_text:
      'Gehaltsspanne (Base): 75.000 – 92.000 EUR Brutto/Jahr · OTE inkl. Variable: 110.000 – 135.000 EUR. Die Einstufung erfolgt anhand objektiver Kriterien (nachgewiesene Track-Record-Quota, Branchen-Erfahrung).',
    created_by: '{{OWNER_USER}}',
    _note: 'Demo: zeigt Draft-State — noch nicht veröffentlicht, aber bereits Compliance-konform vorbereitet.',
  },
  {
    id: '{{uuid_jpost_03}}',
    organization_id: '{{ORG_ID}}',
    title: 'Marketing Manager Mid (m/w/d) · Berlin',
    job_profile_id: '{{uuid_jp_mkt_mgr}}',
    job_level_id: '{{uuid_lvl_mid}}',
    department_id: '{{uuid_dept_marketing}}',
    salary_range_min: 58000,
    salary_range_max: 72000,
    currency: 'EUR',
    location: 'Berlin',
    employment_type: 'full_time',
    status: 'closed',
    salary_disclosed: true,
    published_at: '2024-09-01T10:00:00Z',
    closed_at: '2024-10-31T17:00:00Z',
    description:
      'Marketing Manager für Demand Generation & Performance. SEA, SEO, Content. 3+ Jahre Erfahrung.',
    export_text:
      'Gehaltsspanne: 58.000 – 72.000 EUR Brutto/Jahr (40h/Woche). Stelle besetzt durch Lisa Berger (Eintritt 2023-03-15, externe Bewerbung). Closed.',
    created_by: '{{OWNER_USER}}',
    _note: 'Demo: zeigt Historie — abgeschlossene Stelle, dokumentiert für Audit-Trail.',
  },
] as const;

// ─────────────────────────────────────────────────────────────────────────────
// SUMMARY (for demo crib-sheet)
// ─────────────────────────────────────────────────────────────────────────────
//
//   45 employees    25 ♂ / 20 ♀   ≈ 56 / 44%
//    5 departments  Eng 16 · Sales 10 · Marketing 6 · HR 7 · Finance 6
//    5 levels       Junior · Mid · Senior · Lead · Principal
//   12 profiles
//   21 pay bands
//   25 salary decisions  (10 hire · 10 raise · 3 promotion · 2 band_change)
//    3 info requests     (1 open · 1 fulfilled · 1 overdue)
//   10 audit log rows
//    3 job postings      (1 published · 1 draft · 1 closed)
//
//   Engineered gaps (FLAGGED, >5% per Art. 10 EU 2023/970):
//     · Gap-Gruppe A — SWE Senior:   mean ~10.8%   employees #08–#14
//     · Gap-Gruppe B — AE Mid:       mean ~12.1%   employees #26–#30
//
//   Demo seats:
//     · {{OWNER_USER}}  →  Sandra Becker  (HRBP Lead, owner)
//     · {{HR_USER}}     →  Markus Hofer   (HRBP Senior, hr_manager)
//
// ─────────────────────────────────────────────────────────────────────────────
